package com.jarzsoft.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.jarzsoft.entities.W_Wf;

@Repository
public interface W_WfRepository extends JpaRepository<W_Wf, Long> {
	//jarz 17/05/2023 Ajusta el SQL
	@Query(value = "select p.numero_credito, p.saldo_capital, p.estado,t.nitter as nitterPro, fo.nombre_credito, t.nomter as nomTerPro, fc.nom_claaso, ft.nom_tipaso, c.nombciud, a.nom_clase,\r\n"
			+ "(select nomter from  terceros where codter = p.codter_asesor) as asesor, f.cod_emple, \r\n"
			+ "(select nitter from terceros where codter = p.codeudor1) as nitterCod, (select nomter from terceros where codter = p.codeudor1) as nomTerCod,\r\n"
			+ "(select fc1.nom_claaso from foclaaso fc1, fodataso fod1 where  fc1.cod_inter = fod1.cla_asoci and fod1.cod_ter = p.codeudor1 ) as nom_claasoCod,\r\n"
			+ " ( select CASE Ind_est_pesona WHEN '1' THEN 'Activo /Laborando' WHEN '2' THEN 'Retirado' WHEN '3' THEN 'Fallecido' ELSE 'Sin Marcación' end from terceros where codter = p.codter) as est_personaDeu, \r\n"
			+ " ( select CASE Ind_est_pesona WHEN '1' THEN 'Activo /Laborando' WHEN '2' THEN 'Retirado' WHEN '3' THEN 'Fallecido' ELSE 'Sin Marcación' end from terceros where codter = p.codeudor1) as est_personaCoDeu, \r\n"
			+ " CASE marcacion WHEN 'A' THEN 'Al día' WHEN 'P' THEN 'Provisionado' WHEN 'J' THEN 'Jurídico' WHEN 'M' THEN 'Moroso' WHEN 'C' THEN 'Castigado' ELSE 'Sin Marcación' end as marcacionn,\r\n"
			+ "  p.v_solicita as Valor_moraK, p.v_solicita as Valor_moraI, p.v_solicita as Valor_moraO, p.v_solicita as Valor_mora, p.nro_cuotas as cuoMora,\r\n"
			+ "  (p.v_solicita -   \r\n"
			+ "  ( select isnull(sum(a.valor_capital_caja + a.valor_capital_nomina + a.valor_extra + a.valor_prima ),0) as valor\r\n"
			+ "	from apo_not_cre_prestamo a, apo_not_credito an  where a.num_nota = an.num_nota and a.tip_comp = an.tip_comp and an.anu_nota <> 'A' and a.nro_credito = p.numero_credito)  ) as saldoK, 'Deudor' as indicador\r\n"
			+ " from prestamo p, terceros t, fodataso f, fotipcre fo, foclaaso fc, fotipaso ft, ciudades c, apo_T_Cla_Aso_1 a\r\n"
			+ " where p.codter = t.codter\r\n"
			+ " and p.REFINANCIA = 0\r\n"
			+ " and p.codter = f.cod_ter\r\n"
			+ " and p.tipo_credito = fo.codigo_credito\r\n"
			+ " and fc.cod_inter = f.cla_asoci\r\n"
			+ " and ft.cod_inter = f.tip_asoci\r\n"
			+ " and f.CIU_DISTRITO = c.codiciud\r\n"
			+ " and f.cla_aso_1 = a.id_cla_aso_1\r\n"
			+ " and p.codter =  :codTer\r\n"
			+ " and p.estado = 'A'\r\n"
			+ " union all\r\n"
			+ " select p.numero_credito, p.saldo_capital, p.estado, t.nitter as nitterPro, fo.nombre_credito, t.nomter as nomTerPro, fc.nom_claaso, ft.nom_tipaso, c.nombciud, a.nom_clase,\r\n"
			+ " (select nomter from  terceros where codter = p.codter_asesor) as asesor, f.cod_emple,\r\n"
			+ "(select nitter from terceros where codter = p.codeudor1) as nitterCod, (select nomter from terceros where codter = p.codeudor1) as nomTerCod,\r\n"
			+ "(select fc1.nom_claaso from foclaaso fc1, fodataso fod1 where  fc1.cod_inter = fod1.cla_asoci and fod1.cod_ter = p.codeudor1 ) as nom_claasoCod,\r\n"
			+ " ( select CASE Ind_est_pesona WHEN '1' THEN 'Activo /Laborando' WHEN '2' THEN 'Retirado' WHEN '3' THEN 'Fallecido' ELSE 'Sin Marcación' end from terceros where codter = p.codter) as est_personaDeu, \r\n"
			+ " ( select CASE Ind_est_pesona WHEN '1' THEN 'Activo /Laborando' WHEN '2' THEN 'Retirado' WHEN '3' THEN 'Fallecido' ELSE 'Sin Marcación' end from terceros where codter = p.codeudor1) as est_personaCoDeu, \r\n"
			+ " CASE marcacion WHEN 'A' THEN 'Al día' WHEN 'P' THEN 'Provisionado' WHEN 'J' THEN 'Jurídico' WHEN 'M' THEN 'Moroso' WHEN 'C' THEN 'Castigado' ELSE 'Sin Marcación' end as marcacionn,\r\n"
			+ "  p.v_solicita as Valor_moraK, p.v_solicita as Valor_moraI, p.v_solicita as Valor_moraO, p.v_solicita as Valor_mora, p.nro_cuotas as cuoMora,\r\n"
			+ "  (p.v_solicita -   \r\n"
			+ "  ( select isnull(sum(a.valor_capital_caja + a.valor_capital_nomina + a.valor_extra + a.valor_prima ),0) as valor\r\n"
			+ "	from apo_not_cre_prestamo a, apo_not_credito an  where a.num_nota = an.num_nota and a.tip_comp = an.tip_comp and an.anu_nota <> 'A' and a.nro_credito = p.numero_credito)  ) as saldoK, 'Codeudor' as indicador\r\n"
			+ " from prestamo p, terceros t, fodataso f, fotipcre fo, foclaaso fc, fotipaso ft, ciudades c, apo_T_Cla_Aso_1 a\r\n"
			+ " where p.codter = t.codter and p.codeudor1 <> 0\r\n"
			+ " and p.REFINANCIA = 0\r\n"
			+ " and p.codter = f.cod_ter\r\n"
			+ " and p.tipo_credito = fo.codigo_credito\r\n"
			+ " and fc.cod_inter = f.cla_asoci\r\n"
			+ " and ft.cod_inter = f.tip_asoci\r\n"
			+ " and f.CIU_DISTRITO = c.codiciud\r\n"
			+ " and f.cla_aso_1 = a.id_cla_aso_1\r\n"
			+ " and p.codeudor1  = :codTer\r\n"
			+ " and p.estado = 'A'\r\n"
			+ " union all\r\n"
			+ " select p.numero_credito, p.saldo_capital, p.estado,t.nitter as nitterPro, fo.nombre_credito, t.nomter as nomTerPro, fc.nom_claaso, ft.nom_tipaso, c.nombciud, a.nom_clase,\r\n"
			+ " (select nomter from  terceros where codter = p.codter_asesor) as asesor, f.cod_emple,\r\n"
			+ "(select nitter from terceros where codter = p.codeudor2) as nitterCod, (select nomter from terceros where codter = p.codeudor2) as nomTerCod,\r\n"
			+ "(select fc1.nom_claaso from foclaaso fc1, fodataso fod1 where  fc1.cod_inter = fod1.cla_asoci and fod1.cod_ter = p.codeudor2 ) as nom_claasoCod,\r\n"
			+ " ( select CASE Ind_est_pesona WHEN '1' THEN 'Activo /Laborando' WHEN '2' THEN 'Retirado' WHEN '3' THEN 'Fallecido' ELSE 'Sin Marcación' end from terceros where codter = p.codter) as est_personaDeu, \r\n"
			+ " ( select CASE Ind_est_pesona WHEN '1' THEN 'Activo /Laborando' WHEN '2' THEN 'Retirado' WHEN '3' THEN 'Fallecido' ELSE 'Sin Marcación' end from terceros where codter = p.codeudor2) as est_personaCoDeu, \r\n"
			+ " CASE marcacion WHEN 'A' THEN 'Al día' WHEN 'P' THEN 'Provisionado' WHEN 'J' THEN 'Jurídico' WHEN 'M' THEN 'Moroso' WHEN 'C' THEN 'Castigado' ELSE 'Sin Marcación' end as marcacionn,\r\n"
			+ "  p.v_solicita as Valor_moraK, p.v_solicita as Valor_moraI, p.v_solicita as Valor_moraO, p.v_solicita as Valor_mora, p.nro_cuotas as cuoMora,\r\n"
			+ "  (p.v_solicita -   \r\n"
			+ "  ( select isnull(sum(a.valor_capital_caja + a.valor_capital_nomina + a.valor_extra + a.valor_prima ),0) as valor\r\n"
			+ "	from apo_not_cre_prestamo a, apo_not_credito an  where a.num_nota = an.num_nota and a.tip_comp = an.tip_comp and an.anu_nota <> 'A' and a.nro_credito = p.numero_credito)  ) as saldoK, 'Codeudor' as indicador\r\n"
			+ " from prestamo p, terceros t, fodataso f, fotipcre fo, foclaaso fc, fotipaso ft, ciudades c, apo_T_Cla_Aso_1 a\r\n"
			+ " where p.codter = t.codter and p.codeudor2 <> 0\r\n"
			+ " and p.REFINANCIA = 0\r\n"
			+ " and p.codter = f.cod_ter\r\n"
			+ " and p.tipo_credito = fo.codigo_credito\r\n"
			+ " and fc.cod_inter = f.cla_asoci\r\n"
			+ " and ft.cod_inter = f.tip_asoci\r\n"
			+ " and f.CIU_DISTRITO = c.codiciud\r\n"
			+ " and f.cla_aso_1 = a.id_cla_aso_1\r\n"
			+ " and p.codeudor2  =  :codTer\r\n"
			+ " and p.estado = 'A'\r\n"
			+ " union all\r\n"
			+ " select p.numero_credito, p.saldo_capital, p.estado,t.nitter as nitterPro, fo.nombre_credito, t.nomter as nomTerPro, fc.nom_claaso, ft.nom_tipaso, c.nombciud, a.nom_clase,\r\n"
			+ " (select nomter from  terceros where codter = p.codter_asesor) as asesor, f.cod_emple,\r\n"
			+ "(select nitter from terceros where codter = p.codeudor3) as nitterCod, (select nomter from terceros where codter = p.codeudor3) as nomTerCod,\r\n"
			+ "(select fc1.nom_claaso from foclaaso fc1, fodataso fod1 where  fc1.cod_inter = fod1.cla_asoci and fod1.cod_ter = p.codeudor3 ) as nom_claasoCod,\r\n"
			+ " ( select CASE Ind_est_pesona WHEN '1' THEN 'Activo /Laborando' WHEN '2' THEN 'Retirado' WHEN '3' THEN 'Fallecido' ELSE 'Sin Marcación' end from terceros where codter = p.codter) as est_personaDeu, \r\n"
			+ " ( select CASE Ind_est_pesona WHEN '1' THEN 'Activo /Laborando' WHEN '2' THEN 'Retirado' WHEN '3' THEN 'Fallecido' ELSE 'Sin Marcación' end from terceros where codter = p.codeudor3) as est_personaCoDeu, \r\n"
			+ " CASE marcacion WHEN 'A' THEN 'Al día' WHEN 'P' THEN 'Provisionado' WHEN 'J' THEN 'Jurídico' WHEN 'M' THEN 'Moroso' WHEN 'C' THEN 'Castigado' ELSE 'Sin Marcación' end as marcacionn,\r\n"
			+ "  p.v_solicita as Valor_moraK, p.v_solicita as Valor_moraI, p.v_solicita as Valor_moraO, p.v_solicita as Valor_mora, p.nro_cuotas as cuoMora,\r\n"
			+ "  (p.v_solicita -   \r\n"
			+ "  ( select isnull(sum(a.valor_capital_caja + a.valor_capital_nomina + a.valor_extra + a.valor_prima ),0) as valor\r\n"
			+ "	from apo_not_cre_prestamo a, apo_not_credito an  where a.num_nota = an.num_nota and a.tip_comp = an.tip_comp and an.anu_nota <> 'A' and a.nro_credito = p.numero_credito)  ) as saldoK, 'Codeudor' as indicador\r\n"
			+ " from prestamo p, terceros t, fodataso f, fotipcre fo, foclaaso fc, fotipaso ft, ciudades c, apo_T_Cla_Aso_1 a\r\n"
			+ " where p.codter = t.codter and p.codeudor3 <> 0\r\n"
			+ " and p.REFINANCIA = 0\r\n"
			+ " and p.codter = f.cod_ter\r\n"
			+ " and p.tipo_credito = fo.codigo_credito\r\n"
			+ " and fc.cod_inter = f.cla_asoci\r\n"
			+ " and ft.cod_inter = f.tip_asoci\r\n"
			+ " and f.CIU_DISTRITO = c.codiciud\r\n"
			+ " and f.cla_aso_1 = a.id_cla_aso_1\r\n"
			+ " and p.codeudor3  =  :codTer\r\n"
			+ " and p.estado = 'A'\r\n"
			+ " union all\r\n"
			+ " select p.numero_credito, p.saldo_capital, p.estado,t.nitter as nitterPro, fo.nombre_credito, t.nomter as nomTerPro, fc.nom_claaso, ft.nom_tipaso, c.nombciud, a.nom_clase,\r\n"
			+ " (select nomter from  terceros where codter = p.codter_asesor) as asesor, f.cod_emple,\r\n"
			+ "(select nitter from terceros where codter = p.codeudor4) as nitterCod, (select nomter from terceros where codter = p.codeudor4) as nomTerCod,\r\n"
			+ "(select fc1.nom_claaso from foclaaso fc1, fodataso fod1 where  fc1.cod_inter = fod1.cla_asoci and fod1.cod_ter = p.codeudor4 ) as nom_claasoCod,\r\n"
			+ " ( select CASE Ind_est_pesona WHEN '1' THEN 'Activo /Laborando' WHEN '2' THEN 'Retirado' WHEN '3' THEN 'Fallecido' ELSE 'Sin Marcación' end from terceros where codter = p.codter) as est_personaDeu, \r\n"
			+ " ( select CASE Ind_est_pesona WHEN '1' THEN 'Activo /Laborando' WHEN '2' THEN 'Retirado' WHEN '3' THEN 'Fallecido' ELSE 'Sin Marcación' end from terceros where codter = p.codeudor4) as est_personaCoDeu, \r\n"
			+ " CASE marcacion WHEN 'A' THEN 'Al día' WHEN 'P' THEN 'Provisionado' WHEN 'J' THEN 'Jurídico' WHEN 'M' THEN 'Moroso' WHEN 'C' THEN 'Castigado' ELSE 'Sin Marcación' end as marcacionn,\r\n"
			+ "  p.v_solicita as Valor_moraK, p.v_solicita as Valor_moraI, p.v_solicita as Valor_moraO, p.v_solicita as Valor_mora, p.nro_cuotas as cuoMora,\r\n"
			+ "  (p.v_solicita -   \r\n"
			+ "  ( select isnull(sum(a.valor_capital_caja + a.valor_capital_nomina + a.valor_extra + a.valor_prima ),0) as valor\r\n"
			+ "	from apo_not_cre_prestamo a, apo_not_credito an  where a.num_nota = an.num_nota and a.tip_comp = an.tip_comp and an.anu_nota <> 'A' and a.nro_credito = p.numero_credito)  ) as saldoK, 'Codeudor' as indicador\r\n"
			+ " from prestamo p, terceros t, fodataso f, fotipcre fo, foclaaso fc, fotipaso ft, ciudades c, apo_T_Cla_Aso_1 a\r\n"
			+ " where p.codter = t.codter and p.codeudor4 <> 0\r\n"
			+ " and p.REFINANCIA = 0\r\n"
			+ " and p.codter = f.cod_ter\r\n"
			+ " and p.tipo_credito = fo.codigo_credito\r\n"
			+ " and fc.cod_inter = f.cla_asoci\r\n"
			+ " and ft.cod_inter = f.tip_asoci\r\n"
			+ " and f.CIU_DISTRITO = c.codiciud\r\n"
			+ " and f.cla_aso_1 = a.id_cla_aso_1\r\n"
			+ " and p.codeudor4  =  :codTer\r\n"
			+ " and p.estado = 'A'\r\n"
			+ " order by t.nomter, p.numero_credito", nativeQuery = true)
	List<Object[]> findPortafolio(@Param("codTer") String codTer);

}
