package com.jarzsoft.mapper.impl;

import org.springframework.stereotype.Service;

import com.jarzsoft.dto.DTOSolCredito;
import com.jarzsoft.dto.DTOWF;
import com.jarzsoft.entities.SolCredito;
import com.jarzsoft.mapper.ISolCreditoMapper;

@Service
public class SolCreditoMapper implements ISolCreditoMapper {

	@Override
	public SolCredito mapperDtoToEntitie(DTOSolCredito o) {
		SolCredito out = new SolCredito();
		out.setBienAfecta(o.getBienAfecta());
		out.setBienAfectaCod(o.getBienAfectaCod());
		out.setBienHipAfavor(o.getBienHipAfavor());
		out.setBienHipAfavorCod(o.getBienHipAfavorCod());
		out.setBienHipoteca(o.getBienHipoteca());
		out.setBienHipotecaCod(o.getBienHipotecaCod());
		out.setBienNombre(o.getBienNombre());
		out.setBienNombreCod(o.getBienNombreCod());
		out.setBienValor(o.getBienValor());
		out.setBienValorCod(o.getBienValorCod());
		out.setCodeudor1(o.getCodeudor1());
		out.setCodTer(o.getCodTer());
		out.setNroCuotas(o.getNroCuotas());
		out.setNumeroRadicacion(o.getNumeroRadicacion());
		out.setRefCel1(o.getRefCel1());
		out.setRefCel1Cod(o.getRefCel1Cod());
		out.setRefCel2(o.getRefCel2());
		out.setRefCel2Cod(o.getRefCel2Cod());
		out.setRefCel3(o.getRefCel3());
		out.setRefCel3Cod(o.getRefCel3Cod());
		out.setRefMail1(o.getRefMail1());
		out.setRefMail1Cod(o.getRefMail1Cod());
		out.setRefMail2(o.getRefMail2());
		out.setRefMail2Cod(o.getRefMail2Cod());
		out.setRefMail3(o.getRefMail3());
		out.setRefMail3Cod(o.getRefMail3Cod());
		out.setRefNombre1(o.getRefNombre1());
		out.setRefNombre1Cod(o.getRefNombre1Cod());
		out.setRefNombre2(o.getRefNombre2());
		out.setRefNombre2Cod(o.getRefNombre2Cod());
		out.setRefNombre3(o.getRefNombre3());
		out.setRefNombre3Cod(o.getRefNombre3Cod());
		out.setRefParen1(o.getRefParen1());
		out.setRefParen1Cod(o.getRefParen1Cod());
		out.setRefParen2(o.getRefParen2());
		out.setRefParen2Cod(o.getRefParen2Cod());
		out.setRefParen3(o.getRefParen3());
		out.setRefParen3Cod(o.getRefParen3Cod());
		out.setTipoCredito(o.getTipoCredito());
		out.setValorPres(o.getValorPres());
		out.setVehClase(o.getVehClase());
		out.setVehClaseCod(o.getVehClaseCod());
		out.setVehMarca(o.getVehMarca());
		out.setVehModelo(o.getVehModelo());		
		out.setVehMarcaCod(o.getVehMarcaCod());
		out.setVehModeloCod(o.getVehModeloCod());
		out.setVehPigAfavor(o.getVehPigAfavor());
		out.setVehPigAfavorCod(o.getVehPigAfavorCod());
		out.setVehPignorado(o.getVehPignorado());
		out.setVehPignoradoCod(o.getVehPignoradoCod());
		out.setVehPlaca(o.getVehPlaca());
		out.setVehPlacaCod(o.getVehPlacaCod());
		out.setVehValComercial(o.getVehValComercial());
		out.setVehValComercialCod(o.getVehValComercialCod());
		out.setObsCentrales(o.getObsCentrales());
		out.setNroCuenta(o.getNroCuenta());
		out.setValorAdmo(o.getValorAdmo());
		out.setValorInte(o.getValorInte());
		out.setValorNeto(o.getValorNeto());
		out.setValorCuot(o.getValorCuot());
		out.setSaldo(o.getSaldo());
		out.setEstado(o.getEstado());
		out.setTipo(o.getTipo());
		out.setTasaInt(o.getTasaInt());
		out.setObserva(o.getObserva());
		out.setFechaSoli(o.getFechaSoli());
		out.setCodterAsesor(o.getCodterAsesor());
		out.setTipSolcredito(o.getTipSolcredito());
		return out;
	}

	@Override
	public DTOSolCredito mapperEntitieToDao(SolCredito o) {
		DTOSolCredito out = new DTOSolCredito();
		out.setBienAfecta(o.getBienAfecta());
		out.setBienAfectaCod(o.getBienAfectaCod());
		out.setBienHipAfavor(o.getBienHipAfavor());
		out.setBienHipAfavorCod(o.getBienHipAfavorCod());
		out.setBienHipoteca(o.getBienHipoteca());
		out.setBienHipotecaCod(o.getBienHipotecaCod());
		out.setBienNombre(o.getBienNombre());
		out.setBienNombreCod(o.getBienNombreCod());
		out.setBienValor(o.getBienValor());
		out.setBienValorCod(o.getBienValorCod());
		out.setCodeudor1(o.getCodeudor1());
		out.setCodTer(o.getCodTer());
		out.setNroCuotas(o.getNroCuotas());
		out.setNumeroRadicacion(o.getNumeroRadicacion());
		out.setRefCel1(o.getRefCel1());
		out.setRefCel1Cod(o.getRefCel1Cod());
		out.setRefCel2(o.getRefCel2());
		out.setRefCel2Cod(o.getRefCel2Cod());
		out.setRefCel3(o.getRefCel3());
		out.setRefCel3Cod(o.getRefCel1Cod());
		out.setRefMail1(o.getRefMail1());
		out.setRefMail1Cod(o.getRefMail1Cod());
		out.setRefMail2(o.getRefMail2());
		out.setRefMail2Cod(o.getRefMail2Cod());
		out.setRefMail3(o.getRefMail3());
		out.setRefMail3Cod(o.getRefMail3Cod());
		out.setRefNombre1(o.getRefNombre1());
		out.setRefNombre1Cod(o.getRefNombre1Cod());
		out.setRefNombre2(o.getRefNombre2());
		out.setRefNombre2Cod(o.getRefNombre2Cod());
		out.setRefNombre3(o.getRefNombre3());
		out.setRefNombre3Cod(o.getRefNombre3Cod());
		out.setRefParen1(o.getRefParen1());
		out.setRefParen1Cod(o.getRefParen1Cod());
		out.setRefParen2(o.getRefParen2());
		out.setRefParen2Cod(o.getRefParen2Cod());
		out.setRefParen3(o.getRefParen3());
		out.setRefParen3Cod(o.getRefParen3Cod());
		out.setTipoCredito(o.getTipoCredito());
		out.setTipSolcredito(o.getTipSolcredito());
		out.setValorPres(o.getValorPres());
		out.setVehClase(o.getVehClase());
		out.setVehClaseCod(o.getVehClaseCod());
		out.setVehMarca(o.getVehMarca());
		out.setVehModelo(o.getVehModelo());
		out.setVehMarcaCod(o.getVehMarcaCod());
		out.setVehModeloCod(o.getVehModeloCod());
		out.setVehPigAfavor(o.getVehPigAfavor());
		out.setVehPigAfavorCod(o.getVehPigAfavorCod());
		out.setVehPignorado(o.getVehPignorado());
		out.setVehPignoradoCod(o.getVehPignoradoCod());
		out.setVehPlaca(o.getVehPlaca());
		out.setVehPlacaCod(o.getVehPlacaCod());
		out.setVehValComercial(o.getVehValComercial());
		out.setVehValComercialCod(o.getVehValComercialCod());
		out.setObsCentrales(o.getObsCentrales());
		out.setNroCuenta(o.getNroCuenta());
		out.setValorAdmo(o.getValorAdmo());
		out.setValorInte(o.getValorInte());
		out.setValorNeto(o.getValorNeto());
		out.setValorCuot(o.getValorCuot());
		out.setSaldo(o.getSaldo());
		out.setEstado(o.getEstado());
		out.setTipo(o.getTipo());
		out.setTasaInt(o.getTasaInt());		
		out.setObserva(o.getObserva());
		out.setCodterAsesor(o.getCodterAsesor());
		return out;
	}

	@Override
	public DTOSolCredito mapperDaoToDto(DTOWF o, String codTer, String codeudor,String user,String state) {
		DTOSolCredito out = new DTOSolCredito();
		out.setBienAfecta(o.getBienAfecta());
		out.setBienAfectaCod(o.getCodeu().getBienAfecta());
		out.setBienHipAfavor(o.getBienHipAFavor());
		out.setBienHipAfavorCod(o.getCodeu().getBienHipAFavor());
		out.setBienHipoteca(o.getBienHipoteca());
		out.setBienHipotecaCod(o.getCodeu().getBienHipoteca());
		out.setBienNombre(o.getBienNombre());
		out.setBienNombreCod(o.getCodeu().getBienNombre());
		out.setBienValor(o.getBienValor());
		out.setBienValorCod(o.getCodeu().getBienValor());
		out.setCodeudor1(codeudor);
		out.setCodTer(codTer);
		out.setNroCuotas(o.getNroCuotas());
		out.setNumeroRadicacion(o.getNumeroRadicacion());
		out.setRefCel1(o.getRefCel1());
		out.setRefCel1Cod(o.getCodeu().getRefCel1());
		out.setRefCel2(o.getRefCel2());
		out.setRefCel2Cod(o.getCodeu().getRefCel2());
		out.setRefCel3(o.getRefCel3());
		out.setRefCel3Cod(o.getCodeu().getRefCel3());
		out.setRefMail1(o.getRefMail1());
		out.setRefMail1Cod(o.getCodeu().getRefMail1());
		out.setRefMail2(o.getRefMail2());
		out.setRefMail2Cod(o.getCodeu().getRefMail2());
		out.setRefMail3(o.getRefMail3());
		out.setRefMail3Cod(o.getCodeu().getRefMail3());
		out.setRefNombre1(o.getRefNombre1());
		out.setRefNombre1Cod(o.getCodeu().getRefNombre1());
		out.setRefNombre2(o.getRefNombre2());
		out.setRefNombre2Cod(o.getCodeu().getRefNombre2());
		out.setRefNombre3(o.getRefNombre3());
		out.setRefNombre3Cod(o.getCodeu().getRefNombre3());
		out.setRefParen1(o.getRefParen1());
		out.setRefParen1Cod(o.getCodeu().getRefParen1());
		out.setRefParen2(o.getRefParen2());
		out.setRefParen2Cod(o.getCodeu().getRefParen2());
		out.setRefParen3(o.getRefParen3());
		out.setRefParen3Cod(o.getCodeu().getRefParen3());
		out.setTipoCredito(o.getTipSolCredito());
		out.setTipSolcredito(o.getTipSolCredito());
		out.setValorPres(o.getValorPress());
		out.setVehClase(o.getVehClase());
		out.setVehClaseCod(o.getCodeu().getVehClase());
		out.setVehMarca(o.getVehMarca());
		out.setVehMarcaCod(o.getCodeu().getVehMarca());
		out.setVehModelo(o.getVehModelo());
		out.setVehModeloCod(o.getCodeu().getVehModelo());
		out.setVehPigAfavor(o.getVehPigAFavor());
		out.setVehPigAfavorCod(o.getCodeu().getVehPigAFavor());
		out.setVehPignorado(o.getVehPignorado());
		out.setVehPignoradoCod(o.getCodeu().getVehPignorado());
		out.setVehPlaca(o.getVehPlaca());
		out.setVehPlacaCod(o.getCodeu().getVehPlaca());
		out.setVehValComercial(o.getVehValVomercial());
		out.setVehValComercialCod(o.getCodeu().getVehValVomercial());
		out.setObsCentrales(o.getComments());
		out.setNroCuenta(o.getNumCta());
		out.setValorAdmo("0");
		out.setValorInte("0");
		out.setValorNeto("0");
		out.setValorCuot("0");
		out.setSaldo("0");
		out.setEstado(state);
		out.setTipo(" ");
		out.setTasaInt("0");
		out.setObserva(o.getComments());
		out.setCodterAsesor(user);

		return out;
	}

}
